#!/usr/bin/env python3
"""
kanqiu2m3u.py — 看球吧直播源 → M3U 播放列表

从看球吧（vipkanqiu-cctv.92kq.cn）抓取当前体育直播赛事，
提取 FLV/M3U8 直播流地址，生成标准 M3U 文件。

流无需认证，直接可播。FLV 流需播放器支持 FFmpeg 解码。

Usage:
    python3 kanqiu2m3u.py                     # 获取当前全部直播（默认输出到终端）
    python3 kanqiu2m3u.py -o kanqiu.m3u       # 输出到文件
    python3 kanqiu2m3u.py --match-id 4498962   # 指定比赛 ID
"""

import json
import sys
import os
import argparse
from datetime import datetime
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

# ── 配置 ───────────────────────────────────────────

API_CANDIDATES = [
    "https://zhiboapi3003.zb6.fun",
    "https://zhiboapi1001.bszb.me",
    "https://zhiboapi2002.zb6.fun",
]

API_HOME = "/webapi/home/getHomeData"
API_MATCH_FOOTBALL = "/api/football/getMatchInfo"
API_MATCH_BASKETBALL = "/api/basketball/getMatchInfo"

HEADERS = {
    "Content-Type": "application/json",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "Accept": "application/json",
}

# ── 网络 ────────────────────────────────────────────


def api_post(base, path, data=None):
    url = f"{base}{path}"
    body = json.dumps(data or {}).encode("utf-8")
    req = Request(url, data=body, headers=HEADERS, method="POST")
    try:
        with urlopen(req, timeout=15) as r:
            return json.loads(r.read().decode("utf-8"))
    except (URLError, HTTPError, Exception) as e:
        return {"error": str(e)}


def find_api():
    for base in API_CANDIDATES:
        r = api_post(base, API_HOME, {})
        if r.get("status") == 0:
            return base, r
    return None, None


# ── 数据提取 ────────────────────────────────────────


def extract_recommend_lives(data):
    """从 getHomeData 的 recommend_lives 提取当前直播流"""
    payload = data.get("data", data)  # 兼容 {status, data} 和直接 data
    streams = []
    for live in payload.get("recommend_lives", []):
        url = live.get("pull_url", "") or ""
        if not url:
            continue

        title = live.get("title", "")
        badge = (live.get("badge_text") or "").strip()
        nick = live.get("anchor", {}).get("nick_name", "")
        hot = live.get("hot", 0)
        fmt = "HLS" if ".m3u8" in url else "FLV"

        # 精简频道名：去掉 badge 中已重复的部分
        display = title.strip()
        if nick:
            display += f" [{nick}]"

        streams.append({
            "name": display,
            "url": url,
            "format": fmt,
            "group": badge or "直播",
            "hot": hot,
        })
    return streams


# ── M3U 生成 ─────────────────────────────────────────


def generate_m3u(streams, output=None):
    lines = [
        '#EXTM3U',
        f'# Generated by kanqiu2m3u.py at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
        f'# Source: 看球吧 (vipkanqiu-cctv.92kq.cn)',
        f'# Streams: {len(streams)}',
        '',
    ]

    for s in sorted(streams, key=lambda x: x.get("hot", 0), reverse=True):
        name = s["name"]
        group = s.get("group", "直播")
        fmt = s.get("format", "")
        lines.append(f'#EXTINF:-1 group-title="{group}",{name} [{fmt}]')
        lines.append(s["url"])
        lines.append("")

    content = "\n".join(lines)

    if output:
        os.makedirs(os.path.dirname(output) or ".", exist_ok=True)
        with open(output, "w", encoding="utf-8") as f:
            f.write(content)
        flv = sum(1 for s in streams if s["format"] == "FLV")
        hls = sum(1 for s in streams if s["format"] == "HLS")
        print(f"✅ 已生成: {output}")
        print(f"📺 共 {len(streams)} 路（FLV: {flv}, HLS: {hls}）")
    else:
        print(content)

    return content


# ── 主函数 ──────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description="看球吧直播源 → M3U 播放列表")
    parser.add_argument("-o", "--output", help="输出 M3U 路径（默认终端打印）")
    parser.add_argument("--match-id", type=int, help="指定比赛 ID 获取特定场次")
    parser.add_argument("--sport", type=int, default=1, choices=[1, 2],
                        help="运动类型: 1=足球, 2=篮球（默认 1，仅 --match-id 时生效）")
    args = parser.parse_args()

    print(f"[kanqiu2m3u] 连接 API...", file=sys.stderr)
    base, home_data = find_api()
    if not base:
        print("❌ 所有 API 线路均不可用", file=sys.stderr)
        sys.exit(1)
    print(f"[kanqiu2m3u] ✅ {base}", file=sys.stderr)

    all_streams = []

    if args.match_id:
        ep = API_MATCH_FOOTBALL if args.sport == 1 else API_MATCH_BASKETBALL
        r = api_post(base, ep, {"matchid": args.match_id})
        if r.get("status") != 0:
            print(f"⚠️  API 返回: {r.get('msg', '未知错误')}", file=sys.stderr)
            sys.exit(1)
        data = r.get("data", {})
        for a in data.get("anchors", []):
            live = a.get("live", {})
            url = live.get("pull_url", "")
            if not url:
                continue
            nick = a.get("nick_name", "")
            title = live.get("title", "") or str(args.match_id)
            badge = (live.get("badge_text") or "").strip()
            fmt = "HLS" if ".m3u8" in url else "FLV"
            display = f"{title} [{nick}]" if nick else title
            all_streams.append({
                "name": display,
                "url": url,
                "format": fmt,
                "group": badge or "直播",
                "hot": 0,
            })
    else:
        all_streams = extract_recommend_lives(home_data)

    if not all_streams:
        print("⚠️  当前没有直播中的比赛", file=sys.stderr)
        sys.exit(1)

    generate_m3u(all_streams, args.output)
    return all_streams


if __name__ == "__main__":
    main()
